// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-ZYnpSrzNNdBM6Lw7J4-pY_6JsVxtrQ',
    appId: '1:882348820118:web:2daf252108f9f246b764b7',
    messagingSenderId: '882348820118',
    projectId: 'function-9f57c',
    authDomain: 'function-9f57c.firebaseapp.com',
    storageBucket: 'function-9f57c.appspot.com',
    measurementId: 'G-CZQNCMEKTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe955lI0eqj81xYIHqsvzb5BfrWERoRtM',
    appId: '1:882348820118:android:f028aefdaa251956b764b7',
    messagingSenderId: '882348820118',
    projectId: 'function-9f57c',
    storageBucket: 'function-9f57c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFMOSxfP3YSEWoyPRpG7_X_lBmMHptxM',
    appId: '1:882348820118:ios:9b1b079e563db13fb764b7',
    messagingSenderId: '882348820118',
    projectId: 'function-9f57c',
    storageBucket: 'function-9f57c.appspot.com',
    iosBundleId: 'com.example.emptyflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFMOSxfP3YSEWoyPRpG7_X_lBmMHptxM',
    appId: '1:882348820118:ios:9b1b079e563db13fb764b7',
    messagingSenderId: '882348820118',
    projectId: 'function-9f57c',
    storageBucket: 'function-9f57c.appspot.com',
    iosBundleId: 'com.example.emptyflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-ZYnpSrzNNdBM6Lw7J4-pY_6JsVxtrQ',
    appId: '1:882348820118:web:211f7abd37569e3db764b7',
    messagingSenderId: '882348820118',
    projectId: 'function-9f57c',
    authDomain: 'function-9f57c.firebaseapp.com',
    storageBucket: 'function-9f57c.appspot.com',
    measurementId: 'G-VTVWESEMR3',
  );
}
